volumes:
  data:

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - .:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql
  web:
    build: ./
    restart: unless-stopped
    ports:
      - 8080:8080