services:
  postgres:
    build: ./postgresql
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data

  server:
    build: ./
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - postgres